name: dartshine
description: A lightweight web framework for Dart, designed for clarity, clean syntax, and performance.
version: 2.3.6
repository: https://github.com/ZbrDeev/dartshine
homepage: https://github.com/ZbrDeev/dartshine
issue_tracker: https://github.com/ZbrDeev/dartshine/issues
documentation: https://github.com/ZbrDeev/dartshine/wiki
topics: [backend, web, server, framework]

environment:
  sdk: ^3.4.0

dependencies:
  mime: ^2.0.0
  sqlite3: ^2.9.1
  path: ^1.9.1
  postgresql2: ^1.7.0
  archive: ^4.0.7
  es_compression: ^2.0.15
  uuid: ^4.5.1
  crypto: ^3.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

executables:
  dartshine: dartshine
